import type { Specialty } from "@/lib/specialty-prompts";

export interface Vitals {
  days: number;
  temp: number;
  bpSys: number;
  bpDia: number;
  pulse: number;
}

export interface CaseBlueprint {
  complaint: (v: Vitals) => string;
  examLine: (v: Vitals) => string;
  planLine: (v: Vitals) => string;
  subjective: (v: Vitals) => string;
  objective: (v: Vitals) => string;
  assessment: (v: Vitals) => string;
  plan: (v: Vitals) => string;
  medications: (v: Vitals) => string;
  followUp: (v: Vitals) => string;
}

/** Six reusable case blueprints per specialty. Each is a function of
 * randomly generated vitals so repeated picks for the same doctor don't
 * read as literal duplicates in Session History. */
export const CASE_BANK: Record<Specialty, CaseBlueprint[]> = {
  general: [
    {
      complaint: (v) => `fever for ${v.days} days with body ache`,
      examLine: (v) => `temperature is ${v.temp}F, BP ${v.bpSys}/${v.bpDia}, chest is clear`,
      planLine: () => `paracetamol for the fever and plenty of fluids`,
      subjective: (v) => `Patient reports ${v.days} days of fever with generalized body ache. Mild sore throat, no cough.`,
      objective: (v) => `Temperature ${v.temp}F. BP ${v.bpSys}/${v.bpDia}, pulse ${v.pulse} regular. Throat mildly erythematous. Chest clear on auscultation.`,
      assessment: () => `Viral febrile illness, likely self-limiting upper respiratory viral infection.`,
      plan: () => `Symptomatic management, adequate hydration, and rest. Review if fever persists or worsens.`,
      medications: () => `Paracetamol 650mg every 6 hours as needed for fever.`,
      followUp: () => `Return if fever persists beyond 5 days or breathing difficulty develops.`,
    },
    {
      complaint: (v) => `sugar report came back at ${100 + v.bpSys - 20} fasting`,
      examLine: (v) => `weight is stable, BP ${v.bpSys}/${v.bpDia}, no signs of complications`,
      planLine: () => `adjust the metformin dose and cut back on sugar`,
      subjective: () => `Patient with known type 2 diabetes returns for routine follow-up. Reports difficulty maintaining dietary sugar restriction despite regular walking.`,
      objective: (v) => `Fasting blood glucose ${100 + v.bpSys - 20} mg/dL, mildly elevated. Weight stable. BP ${v.bpSys}/${v.bpDia}. No signs of diabetic complications on exam.`,
      assessment: () => `Suboptimal glycemic control, likely dietary in origin, in an otherwise stable type 2 diabetic.`,
      plan: () => `Increase metformin dose, reinforce dietary counseling, continue current exercise routine.`,
      medications: () => `Metformin 1000mg twice daily (increased from 500mg twice daily).`,
      followUp: () => `Repeat fasting blood glucose and HbA1c in 4 weeks.`,
    },
    {
      complaint: (v) => `running nose and mild cough for ${v.days} days`,
      examLine: (v) => `chest is clear, no fever, temperature ${v.temp}F`,
      planLine: () => `steam inhalation and rest, cough syrup if needed`,
      subjective: (v) => `Patient reports runny nose and mild cough for ${v.days} days. No high fever reported.`,
      objective: (v) => `Temperature ${v.temp}F. Lungs clear bilaterally. Nasal mucosa mildly congested, no purulent discharge.`,
      assessment: () => `Common cold, uncomplicated upper respiratory tract infection.`,
      plan: () => `Supportive care with steam inhalation and rest.`,
      medications: () => `Cough syrup as needed, over-the-counter formulation.`,
      followUp: () => `Return if symptoms persist beyond a week or fever develops.`,
    },
    {
      complaint: (v) => `headaches and BP was high last time, ${v.bpSys}/${v.bpDia} today`,
      examLine: (v) => `BP confirmed ${v.bpSys}/${v.bpDia} on repeat, pulse ${v.pulse}`,
      planLine: () => `start a low-dose antihypertensive and recheck in two weeks`,
      subjective: () => `Patient reports occasional headaches, found to have elevated blood pressure on routine screening. No chest pain or vision changes.`,
      objective: (v) => `BP ${v.bpSys}/${v.bpDia} mmHg on repeat measurement, pulse ${v.pulse} regular. No papilledema. Heart sounds normal.`,
      assessment: () => `Newly detected essential hypertension, stage 1.`,
      plan: () => `Initiate low-dose antihypertensive, advise low-sodium diet and regular exercise.`,
      medications: () => `Amlodipine 5mg once daily.`,
      followUp: () => `Recheck BP in 2 weeks, baseline renal function and ECG advised.`,
    },
    {
      complaint: (v) => `burning in the stomach and acidity for ${v.days} days`,
      examLine: () => `abdomen is soft, mild tenderness in the upper stomach area`,
      planLine: () => `an antacid course and avoid spicy food and skipping meals`,
      subjective: (v) => `Patient reports epigastric burning sensation and acidity for ${v.days} days, worse after meals and on an empty stomach.`,
      objective: () => `Abdomen soft, mild epigastric tenderness on palpation, no guarding or rebound. No pallor.`,
      assessment: () => `Acid peptic disease, likely gastritis related to dietary pattern.`,
      plan: () => `Trial of proton pump inhibitor, dietary modification, avoid NSAIDs and late meals.`,
      medications: () => `Pantoprazole 40mg once daily before breakfast for 2 weeks.`,
      followUp: () => `Review in 2 weeks; endoscopy if symptoms persist despite treatment.`,
    },
    {
      complaint: (v) => `sneezing, itchy eyes and a blocked nose for ${v.days} days`,
      examLine: () => `nasal mucosa looks pale and swollen, lungs are clear`,
      planLine: () => `an antihistamine and avoid the dust or pollen trigger if you can identify it`,
      subjective: (v) => `Patient reports sneezing, itchy watery eyes, and nasal congestion for ${v.days} days, recurring seasonally.`,
      objective: () => `Nasal mucosa pale and boggy, clear watery discharge. Conjunctiva mildly injected. Chest clear.`,
      assessment: () => `Allergic rhinitis, likely seasonal.`,
      plan: () => `Start oral antihistamine, consider nasal steroid spray if symptoms persist, identify and avoid triggers.`,
      medications: () => `Cetirizine 10mg once daily at night.`,
      followUp: () => `Review in 2 weeks if symptoms don't improve.`,
    },
  ],

  cardiology: [
    {
      complaint: (v) => `sometimes I forget to take the BP medicine, today it's ${v.bpSys}/${v.bpDia}`,
      examLine: (v) => `BP is ${v.bpSys}/${v.bpDia}, a bit high, weight is also up slightly`,
      planLine: () => `increase the amlodipine dose and cut down on salt`,
      subjective: () => `Known hypertensive patient reports inconsistent adherence to antihypertensive medication. No chest pain or breathlessness.`,
      objective: (v) => `BP ${v.bpSys}/${v.bpDia} mmHg, elevated from target. Pulse ${v.pulse}. Heart sounds normal, no murmurs.`,
      assessment: () => `Suboptimally controlled essential hypertension, likely due to medication non-adherence and dietary sodium intake.`,
      plan: () => `Increase amlodipine dose, reinforce medication adherence and low-sodium diet, encourage daily walking.`,
      medications: () => `Amlodipine 10mg once daily (increased from 5mg).`,
      followUp: () => `Recheck BP in 2 weeks. Fasting lipid profile at next visit.`,
    },
    {
      complaint: (v) => `chest pain on and off for ${v.days} days, comes when I walk`,
      examLine: (v) => `BP ${v.bpSys}/${v.bpDia}, pulse ${v.pulse}, no acute distress, ordering an ECG`,
      planLine: () => `an ECG and troponin test, and a stress test this week`,
      subjective: () => `Patient reports exertional chest discomfort lasting a few minutes, relieved by rest. Positive family history of cardiac disease.`,
      objective: (v) => `BP ${v.bpSys}/${v.bpDia}, pulse ${v.pulse} regular. ECG ordered, troponin pending. No acute distress on examination.`,
      assessment: () => `Suspected stable angina, possible underlying coronary artery disease given exertional pattern and family history.`,
      plan: () => `Order ECG, troponin, and lipid panel. Schedule stress test within the week.`,
      medications: () => `Aspirin 75mg once daily started as precaution pending workup.`,
      followUp: () => `Review in 1 week with test results. Advise emergency visit if pain occurs at rest.`,
    },
    {
      complaint: () => `feeling fine after the angioplasty, no pain`,
      examLine: () => `access site is healed well, heart sounds normal`,
      planLine: () => `continue the current medicines and avoid heavy lifting a bit longer`,
      subjective: () => `Patient post-angioplasty follow-up, reports no chest pain and good adherence to prescribed cardiac medications.`,
      objective: () => `Access site well healed, no signs of infection or hematoma. Heart sounds normal, no new murmurs.`,
      assessment: () => `Stable post-angioplasty recovery, no complications noted.`,
      plan: () => `Continue current cardiac medication regimen, avoid heavy lifting for another 2 weeks.`,
      medications: () => `Continue dual antiplatelet therapy and statin as previously prescribed.`,
      followUp: () => `Follow-up in 4 weeks with repeat lipid profile.`,
    },
    {
      complaint: (v) => `heart feels like it skips or races sometimes, pulse today is ${v.pulse}`,
      examLine: (v) => `pulse is ${v.pulse}, slightly irregular, ordering an ECG and a 24-hour Holter`,
      planLine: () => `an ECG and Holter monitor to see what's happening`,
      subjective: () => `Patient reports intermittent palpitations, described as skipped or racing heartbeats, no associated chest pain or syncope.`,
      objective: (v) => `Pulse ${v.pulse}, mildly irregular on spot check. BP ${v.bpSys}/${v.bpDia}. Heart sounds otherwise normal.`,
      assessment: () => `Palpitations, possible benign ectopy versus early arrhythmia, pending monitoring.`,
      plan: () => `Order 12-lead ECG and 24-hour Holter monitoring, check thyroid and electrolyte panel.`,
      medications: () => `No new medication started pending workup.`,
      followUp: () => `Review Holter results in 1 to 2 weeks.`,
    },
    {
      complaint: () => `came in for the cholesterol report`,
      examLine: () => `heart sounds normal, discussing the lipid panel results`,
      planLine: () => `start a statin and rework the diet a bit`,
      subjective: () => `Patient presents for review of lipid profile as part of routine cardiac risk assessment. Asymptomatic, no chest pain.`,
      objective: (v) => `BP ${v.bpSys}/${v.bpDia}. LDL cholesterol elevated on recent labs. BMI mildly elevated. Heart sounds normal.`,
      assessment: () => `Dyslipidemia with elevated LDL, moderate cardiovascular risk.`,
      plan: () => `Initiate statin therapy, reinforce low-fat diet and regular aerobic exercise.`,
      medications: () => `Atorvastatin 10mg once daily at night.`,
      followUp: () => `Repeat lipid panel and liver function test in 6 weeks.`,
    },
    {
      complaint: () => `routine check after the heart attack last year`,
      examLine: () => `heart sounds normal, no new symptoms, reviewing the medication list`,
      planLine: () => `continue current medicines and keep up the cardiac rehab exercises`,
      subjective: () => `Patient with prior myocardial infarction returns for routine cardiac follow-up. No chest pain, breathlessness, or palpitations since last visit.`,
      objective: (v) => `BP ${v.bpSys}/${v.bpDia}, pulse ${v.pulse} regular. Heart sounds normal, no murmurs or gallops. No pedal edema.`,
      assessment: () => `Stable post-MI status on secondary prevention therapy.`,
      plan: () => `Continue current secondary prevention regimen, encourage continued cardiac rehabilitation.`,
      medications: () => `Continue aspirin, statin, beta-blocker, and ACE inhibitor as previously prescribed.`,
      followUp: () => `Routine follow-up in 3 months with repeat echocardiogram.`,
    },
  ],

  pediatrics: [
    {
      complaint: () => `came in for the scheduled vaccination`,
      examLine: () => `weight and height are normal for age, no fever`,
      planLine: () => `give the vaccine, some mild fever after is normal`,
      subjective: () => `Child presenting for scheduled booster vaccination. Parent reports no current illness or fever.`,
      objective: () => `Weight and height within normal range for age. No acute distress, afebrile at time of visit.`,
      assessment: () => `Healthy child, due for routine booster immunization.`,
      plan: () => `Administer booster as per immunization schedule. Counsel parent on expected mild post-vaccine fever.`,
      medications: () => `Paracetamol pediatric dose as needed for post-vaccination fever.`,
      followUp: () => `Next scheduled vaccination in 6 months, per immunization calendar.`,
    },
    {
      complaint: (v) => `fever for ${v.days} days and a bit of cough`,
      examLine: (v) => `temperature is ${v.temp}F, chest is clear, no distress`,
      planLine: () => `plenty of fluids and paracetamol syrup if the fever comes back`,
      subjective: (v) => `Child with ${v.days}-day history of fever and mild cough. Parent reports slightly reduced appetite but normal activity level.`,
      objective: (v) => `Temperature ${v.temp}F. Lungs clear on auscultation, no respiratory distress. Throat mildly congested.`,
      assessment: () => `Viral upper respiratory infection in a well-appearing child.`,
      plan: () => `Supportive care, encourage fluids, monitor for worsening symptoms.`,
      medications: () => `Paracetamol pediatric syrup for fever as needed.`,
      followUp: () => `Return if fever persists beyond 3 days or breathing difficulty develops.`,
    },
    {
      complaint: () => `came in for the routine growth checkup`,
      examLine: () => `growth curve is tracking normally, no pallor`,
      planLine: () => `add a bit more iron-rich food like leafy greens to the diet`,
      subjective: () => `Routine well-child visit for growth and nutrition assessment. Parent describes a balanced diet including milk, grains, vegetables, and fruit.`,
      objective: () => `Growth parameters plotted on standard growth chart, tracking along expected percentile curve. No pallor or signs of malnutrition.`,
      assessment: () => `Age-appropriate growth and development, adequate nutritional status.`,
      plan: () => `Encourage increased iron-rich foods such as leafy greens in the diet.`,
      medications: () => `None prescribed at this visit.`,
      followUp: () => `Routine growth check at next scheduled well-child visit in 3 months.`,
    },
    {
      complaint: (v) => `pulling at the ear and fussy for ${v.days} days, mild fever`,
      examLine: (v) => `temperature ${v.temp}F, eardrum looks red and bulging on the right`,
      planLine: () => `a course of antibiotics and paracetamol for the pain`,
      subjective: (v) => `Child reported to be pulling at the ear and irritable for ${v.days} days, with low-grade fever.`,
      objective: (v) => `Temperature ${v.temp}F. Right tympanic membrane erythematous and bulging on otoscopy. Left ear normal.`,
      assessment: () => `Acute otitis media, right ear.`,
      plan: () => `Start antibiotics, analgesia for ear pain, review for resolution.`,
      medications: () => `Amoxicillin pediatric dose three times daily for 5 days, paracetamol for pain.`,
      followUp: () => `Review in 1 week or sooner if fever worsens.`,
    },
    {
      complaint: (v) => `loose motions and vomiting since yesterday, ${v.days} episodes`,
      examLine: () => `mild dehydration signs, abdomen soft, no distension`,
      planLine: () => `oral rehydration solution and a bland diet for a few days`,
      subjective: (v) => `Child with acute onset loose stools and vomiting, approximately ${v.days} episodes since yesterday. Reduced urine output reported.`,
      objective: () => `Mild dehydration signs, dry lips, normal skin turgor. Abdomen soft, non-tender, bowel sounds active.`,
      assessment: () => `Acute gastroenteritis with mild dehydration.`,
      plan: () => `Start oral rehydration solution, bland diet, monitor hydration status closely.`,
      medications: () => `Oral rehydration solution as needed, zinc supplementation for 10 days.`,
      followUp: () => `Return immediately if reduced urination, lethargy, or persistent vomiting.`,
    },
    {
      complaint: () => `wheezing and a bit of trouble breathing when running around`,
      examLine: () => `mild wheeze heard on chest, no severe distress`,
      planLine: () => `a bronchodilator inhaler to use when symptoms come on`,
      subjective: () => `Parent reports child has audible wheeze and mild breathlessness during physical activity, recurring over recent weeks.`,
      objective: () => `Mild expiratory wheeze on chest auscultation bilaterally. No use of accessory muscles, oxygen saturation normal.`,
      assessment: () => `Mild intermittent asthma / reactive airway disease.`,
      plan: () => `Start as-needed bronchodilator inhaler with spacer, avoid known triggers, review technique with parent.`,
      medications: () => `Salbutamol metered-dose inhaler with spacer, as needed.`,
      followUp: () => `Review in 3 to 4 weeks, sooner if wheeze worsens or increases in frequency.`,
    },
  ],

  ent: [
    {
      complaint: (v) => `blocked nose for ${v.days} days and pain over the forehead`,
      examLine: () => `sinus area is tender, some inflammation in the nose`,
      planLine: () => `nasal saline rinses and a decongestant, antibiotics if it doesn't settle`,
      subjective: (v) => `Patient reports ${v.days} days of nasal congestion with facial pressure and headache, worse over the forehead region.`,
      objective: () => `Nasal mucosa inflamed with mild purulent discharge. Tenderness on palpation over frontal sinuses.`,
      assessment: () => `Acute on chronic sinusitis.`,
      plan: () => `Nasal saline irrigation, decongestant, and antibiotics if symptoms persist beyond 7 days.`,
      medications: () => `Amoxicillin-clavulanate 625mg twice daily for 5 days, nasal decongestant spray.`,
      followUp: () => `Review in 1 week, sooner if symptoms worsen.`,
    },
    {
      complaint: (v) => `sore throat for ${v.days} days, hurts to swallow, some fever`,
      examLine: (v) => `temperature ${v.temp}F, tonsils are swollen with white patches`,
      planLine: () => `a course of antibiotics and warm salt water gargles`,
      subjective: () => `Patient reports sore throat with pain on swallowing, associated with low-grade fever.`,
      objective: (v) => `Temperature ${v.temp}F. Tonsils enlarged bilaterally with white exudate. Cervical lymphadenopathy present.`,
      assessment: () => `Acute tonsillitis, likely bacterial given exudate and fever.`,
      plan: () => `Antibiotic course, warm saline gargles, adequate fluid intake.`,
      medications: () => `Amoxicillin 500mg three times daily for 7 days, paracetamol for fever and throat pain.`,
      followUp: () => `Return if not improving in 3 days or difficulty breathing develops.`,
    },
    {
      complaint: () => `trouble hearing for a few months, more in the right ear`,
      examLine: () => `some wax buildup in the right ear canal, ordering a hearing test`,
      planLine: () => `remove the wax first and repeat the hearing test after`,
      subjective: () => `Patient reports progressive difficulty hearing over several months, more pronounced in the right ear.`,
      objective: () => `Otoscopic exam reveals cerumen impaction in the right ear canal. Audiometry ordered to assess degree and type of hearing loss.`,
      assessment: () => `Conductive hearing loss likely related to cerumen impaction, pending audiometry to rule out additional causes.`,
      plan: () => `Cerumen removal followed by repeat audiometric testing.`,
      medications: () => `Ear drops to soften cerumen prior to removal.`,
      followUp: () => `Review audiometry results in 1 week after cerumen removal.`,
    },
    {
      complaint: (v) => `sneezing and itchy nose for ${v.days} days, happens every year around this time`,
      examLine: () => `nasal lining looks pale and swollen, clear discharge`,
      planLine: () => `an antihistamine and a nasal spray for the allergy`,
      subjective: (v) => `Patient reports recurrent sneezing, nasal itching, and clear discharge for ${v.days} days, seasonal pattern noted.`,
      objective: () => `Nasal mucosa pale and edematous with clear watery discharge. No purulence. Throat clear.`,
      assessment: () => `Allergic rhinitis.`,
      plan: () => `Start antihistamine and intranasal corticosteroid spray, identify seasonal triggers.`,
      medications: () => `Fexofenadine 120mg once daily, fluticasone nasal spray once daily.`,
      followUp: () => `Review in 3 weeks if symptoms persist.`,
    },
    {
      complaint: (v) => `dizziness and the room feels like it's spinning, happened ${v.days} times this week`,
      examLine: () => `no nystagmus at rest, hearing seems fine on quick check`,
      planLine: () => `some vestibular exercises and a short course of medicine for the dizziness`,
      subjective: (v) => `Patient reports episodic vertigo with a spinning sensation, occurring ${v.days} times over the past week, no hearing loss reported.`,
      objective: () => `No spontaneous nystagmus at rest. Gross hearing intact bilaterally. Romberg test mildly positive.`,
      assessment: () => `Benign paroxysmal positional vertigo, likely peripheral vestibular cause.`,
      plan: () => `Vestibular repositioning exercises, short course of vestibular suppressant if severe.`,
      medications: () => `Betahistine 16mg twice daily for 2 weeks.`,
      followUp: () => `Review in 2 weeks, refer for vestibular testing if not improving.`,
    },
    {
      complaint: (v) => `voice has been hoarse for ${v.days} days`,
      examLine: () => `throat looks mildly inflamed, voice sounds rough`,
      planLine: () => `voice rest and plenty of fluids, avoid shouting or whispering`,
      subjective: (v) => `Patient reports hoarseness of voice for ${v.days} days, associated with mild throat irritation. No difficulty breathing.`,
      objective: () => `Oropharynx mildly erythematous. Voice quality rough and breathy on assessment. No stridor.`,
      assessment: () => `Acute laryngitis, likely viral or voice-strain related.`,
      plan: () => `Voice rest, adequate hydration, avoid irritants such as smoking and shouting.`,
      medications: () => `Warm saline gargles, throat lozenges as needed.`,
      followUp: () => `Review in 2 weeks if hoarseness persists, consider ENT scope if no improvement.`,
    },
  ],

  dermatology: [
    {
      complaint: () => `pimples improved a bit but some new ones keep coming up`,
      examLine: () => `less redness now, but a few active spots on the cheeks`,
      planLine: () => `continue the cream but at a lower strength to avoid irritation`,
      subjective: () => `Patient on treatment for acne reports partial improvement with some new lesions appearing.`,
      objective: () => `Mild residual erythema, few new inflammatory papules on cheeks and forehead. No scarring noted.`,
      assessment: () => `Acne vulgaris, moderate improvement on current treatment regimen.`,
      plan: () => `Continue topical treatment at a lower strength to reduce irritation while maintaining efficacy.`,
      medications: () => `Adapalene 0.1% gel at night, reduced frequency to alternate nights.`,
      followUp: () => `Review in 4 weeks to assess further improvement.`,
    },
    {
      complaint: (v) => `itchy red patches on the hands and legs for ${v.days} days`,
      examLine: () => `skin looks scaly and red, no sign of infection`,
      planLine: () => `a moisturizer routine and a steroid cream for the active patches`,
      subjective: (v) => `Patient reports itchy red patches on hands and legs for the past ${v.days} days.`,
      objective: () => `Erythematous, scaly patches noted on dorsal hands and shins, consistent with eczematous dermatitis. No signs of secondary infection.`,
      assessment: () => `Atopic eczema, moderate severity.`,
      plan: () => `Regular emollient use, topical corticosteroid for active flares, avoid known irritants.`,
      medications: () => `Hydrocortisone 1% cream twice daily for 1 week, plus daily moisturizer.`,
      followUp: () => `Review in 2 weeks, sooner if worsening or signs of infection appear.`,
    },
    {
      complaint: (v) => `an itchy patch on the leg for ${v.days} days, spreading a bit at the edges`,
      examLine: () => `ring-shaped patch with a clear centre, looks fungal`,
      planLine: () => `an antifungal cream, keep the area dry`,
      subjective: (v) => `Patient presents with new-onset itchy patch on the leg with well-defined erythematous borders, present for ${v.days} days.`,
      objective: () => `Annular scaly lesion with central clearing and raised erythematous border, consistent with dermatophyte infection.`,
      assessment: () => `Tinea corporis, fungal skin infection.`,
      plan: () => `Topical antifungal treatment, keep area dry, avoid sharing personal items.`,
      medications: () => `Clotrimazole 1% cream twice daily for 2 weeks.`,
      followUp: () => `Review in 2 weeks if not resolved, consider oral antifungal if persistent.`,
    },
    {
      complaint: (v) => `thick scaly patches on the elbows and knees for a while now, flaring for ${v.days} days`,
      examLine: () => `well-defined silvery scaly plaques, classic look`,
      planLine: () => `a topical steroid combination and a good moisturizing routine`,
      subjective: (v) => `Patient reports chronic thick scaly patches on elbows and knees, with a flare over the last ${v.days} days.`,
      objective: () => `Well-demarcated erythematous plaques with silvery scale over extensor surfaces of elbows and knees. Nail pitting noted.`,
      assessment: () => `Plaque psoriasis, mild to moderate, currently flaring.`,
      plan: () => `Topical corticosteroid with vitamin D analogue combination, regular emollients, sun exposure in moderation.`,
      medications: () => `Calcipotriol-betamethasone ointment once daily for 4 weeks.`,
      followUp: () => `Review in 4 weeks, consider referral if extensive or not responding.`,
    },
    {
      complaint: (v) => `itchy raised bumps all over the body since yesterday, keeps coming back for ${v.days} days`,
      examLine: () => `raised red welts, some are joining up, no swelling of the lips or tongue`,
      planLine: () => `an antihistamine and trying to figure out what triggered it`,
      subjective: (v) => `Patient reports sudden onset of itchy raised wheals over the body, recurring intermittently over ${v.days} days. No facial or airway swelling.`,
      objective: () => `Multiple erythematous wheals of varying size, some coalescing, over trunk and limbs. No angioedema. Airway clear.`,
      assessment: () => `Acute urticaria, likely allergic or idiopathic.`,
      plan: () => `Start non-sedating antihistamine, identify and avoid possible triggers, escalate if angioedema develops.`,
      medications: () => `Cetirizine 10mg once daily, increase to twice daily if not controlled.`,
      followUp: () => `Review in 2 weeks; seek emergency care if facial swelling or breathing difficulty occurs.`,
    },
    {
      complaint: () => `noticing more hair fall than usual over the last few months`,
      examLine: () => `some diffuse thinning, scalp otherwise looks healthy, no bald patches`,
      planLine: () => `checking iron and thyroid levels and starting a topical treatment`,
      subjective: () => `Patient reports increased hair shedding over several months, noticed more hair on the pillow and in the shower drain.`,
      objective: () => `Diffuse thinning over the crown, no scarring or discrete bald patches. Scalp skin normal, no signs of infection.`,
      assessment: () => `Telogen effluvium versus early androgenetic alopecia, pending workup.`,
      plan: () => `Check iron studies, thyroid function, and vitamin D. Start topical minoxidil.`,
      medications: () => `Minoxidil 5% topical solution once daily.`,
      followUp: () => `Review labs and hair regrowth response in 8 to 12 weeks.`,
    },
  ],
};
