import type { SOAPNote } from "@/lib/claude";

/** Single source of truth for SOAP section order, labels, and print
 * accent colors — shared by the doctor SOAP panel and the patient note
 * detail view so exports stay consistent between the two. */
export const SOAP_SECTIONS: { key: keyof SOAPNote; label: string; hex: string }[] = [
  { key: "subjective",  label: "Subjective",  hex: "#60a5fa" },
  { key: "objective",   label: "Objective",   hex: "#22d3ee" },
  { key: "assessment",  label: "Assessment",  hex: "#fbbf24" },
  { key: "plan",        label: "Plan",        hex: "#a78bfa" },
  { key: "medications", label: "Medications", hex: "#fb7185" },
  { key: "followUp",    label: "Follow-up",   hex: "#fb923c" },
];

const escapeHtml = (text: string) =>
  text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

export function buildNotePlainText(note: SOAPNote): string {
  return SOAP_SECTIONS.map((s) => `${s.label}:\n${note[s.key]}`).join("\n\n");
}

export function downloadNoteTxt(note: SOAPNote, filenamePrefix = "soap-note"): void {
  const text = `SOAP NOTE\n${"=".repeat(40)}\n\n${SOAP_SECTIONS.map(
    (s) => `${s.label.toUpperCase()}:\n${note[s.key]}`
  ).join("\n\n" + "-".repeat(40) + "\n\n")}`;
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filenamePrefix}-${new Date().toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printNote(
  note: SOAPNote,
  meta?: { title?: string; dateLabel?: string }
): void {
  const date =
    meta?.dateLabel ??
    new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

  // Print output always stays light and paper-styled, since a printed
  // clinical record should read cleanly regardless of the app's theme.
  const sectionsHtml = SOAP_SECTIONS.map(
    (s) => `
      <div style="margin-bottom:20px;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
          <span style="display:inline-block;width:3px;height:18px;background:${s.hex};margin-right:2px;"></span>
          <h3 style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:0.07em;color:#555;font-weight:600;">${s.label}</h3>
        </div>
        <p style="margin:0;font-size:14px;line-height:1.65;color:#1a1a1a;white-space:pre-wrap;padding-left:11px;">${escapeHtml(note[s.key])}</p>
      </div>
      ${s.key !== "followUp" ? '<hr style="border:none;border-top:1px solid #efefef;margin:16px 0;" />' : ""}
    `
  ).join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8" /><title>${meta?.title ?? "SOAP Note"} | PolyScribe</title>
<style>
  @media print { body { margin:0; } @page { margin:20mm 15mm; } }
  body { font-family:'Plus Jakarta Sans',ui-sans-serif,system-ui,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a; }
</style></head><body>
  <div style="border-bottom:2px solid #0d9488;padding-bottom:12px;margin-bottom:24px;">
    <h1 style="margin:0;font-size:20px;color:#0d9488;">PolyScribe</h1>
    <p style="margin:4px 0 0;font-size:11px;color:#888;">Multilingual AI Clinical Scribe</p>
  </div>
  <div style="margin-bottom:24px;">
    <h2 style="margin:0;font-size:18px;">${meta?.title ?? "SOAP Note"}</h2>
    <p style="margin:4px 0 0;font-size:12px;color:#888;">${date}</p>
  </div>
  ${sectionsHtml}
  <div style="margin-top:32px;padding-top:12px;border-top:1px solid #e5e5e5;font-size:11px;color:#aaa;text-align:center;">
    Generated by PolyScribe. Audio deleted after note generation
  </div>
</body></html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 300);
  }
}
